INSERT INTO medicamentosConsulta (nomeMedicamento, fabricante, tipo, uso) VALUES
('Dipirona', 'Genérico', 'Analgésico', 'Dor de cabeça, febre, dor muscular'),
('Paracetamol', 'Genérico', 'Analgésico', 'Dor de cabeça, febre'),
('Ibuprofeno', 'Genérico', 'Anti-inflamatório', 'Dor muscular, inflamação'),
('Omeprazol', 'Genérico', 'Inibidor de bomba de prótons', 'Refluxo ácido, úlcera péptica'),
('Amoxicilina', 'Genérico', 'Antibiótico', 'Infecções bacterianas, sinusite'),
('Dexametasona', 'Genérico', 'Corticosteroide', 'Inflamações, alergias'),
('Cloridrato de Ciprofloxacino', 'Genérico', 'Antibiótico', 'Infecções bacterianas, cistite'),
('Dipirona Sódica + Cafeína', 'Genérico', 'Analgésico', 'Dor de cabeça, enxaqueca'),
('Cetoprofeno', 'Genérico', 'Anti-inflamatório', 'Dor muscular, inflamação'),
('Cloridrato de Tramadol', 'Genérico', 'Analgésico opioide', 'Dor moderada a severa'),
('Ranitidina', 'Genérico', 'Antagonista dos receptores H2', 'Úlcera péptica, refluxo ácido'),
('Azitromicina', 'Genérico', 'Antibiótico', 'Infecções respiratórias, sinusite'),
('Dipirona Sódica', 'Genérico', 'Analgésico', 'Dor de cabeça, febre'),
('Prednisona', 'Genérico', 'Corticosteroide', 'Inflamações, alergias'),
('Cefalexina', 'Genérico', 'Antibiótico', 'Infecções bacterianas, infecções de pele'),
('Metformina', 'Genérico', 'Hipoglicemiante', 'Diabetes tipo 2'),
('Sinvastatina', 'Genérico', 'Estatina', 'Colesterol alto, prevenção de doenças cardiovasculares'),
('Losartana Potássica', 'Genérico', 'Bloqueador do receptor de angiotensina II', 'Hipertensão arterial, insuficiência cardíaca'),
('Hidroclorotiazida', 'Genérico', 'Diurético', 'Hipertensão arterial, edema'),
('Loratadina', 'Genérico', 'Antialérgico', 'Rinite alérgica, urticária'),
('Enalapril', 'Genérico', 'Inibidor da enzima conversora de angiotensina (IECA)', 'Hipertensão arterial, insuficiência cardíaca'),
('Diclofenaco Sódico', 'Genérico', 'Anti-inflamatório não esteroide (AINE)', 'Dor muscular, inflamação'),
('Metronidazol', 'Genérico', 'Antibiótico', 'Infecções bacterianas, infecções parasitárias'),
('Nimesulida', 'Genérico', 'Anti-inflamatório não esteroide (AINE)', 'Dor leve a moderada, inflamação'),
('Cloridrato de Sertralina', 'Genérico', 'Inibidor seletivo da recaptação de serotonina (ISRS)', 'Depressão, transtorno obsessivo-compulsivo (TOC)'),
('Levotiroxina Sódica', 'Genérico', 'Hormônio da tireoide', 'Hipotireoidismo'),
('Dextrometorfano', 'Genérico', 'Antitussígeno', 'Tosse seca'),
('Lansoprazol', 'Genérico', 'Inibidor de bomba de prótons', 'Refluxo ácido, úlcera péptica'),
('Ceftriaxona', 'Genérico', 'Antibiótico', 'Infecções bacterianas graves, meningite'),
('Fluconazol', 'Genérico', 'Antifúngico', 'Infecções fúngicas, candidíase'),
('Bromoprida', 'Genérico', 'Antiemético', 'Náuseas, vômitos'),
('Sulfato de Salbutamol', 'Genérico', 'Broncodilatador', 'Asma, doença pulmonar obstrutiva crônica (DPOC)'),
('Olanzapina', 'Genérico', 'Antipsicótico', 'Esquizofrenia, transtorno bipolar'),
('Pantoprazol', 'Genérico', 'Inibidor de bomba de prótons', 'Refluxo ácido, úlcera péptica'),
('Amitriptilina', 'Genérico', 'Antidepressivo tricíclico', 'Depressão, dor crônica'),
('Ciprofloxacino', 'Genérico', 'Antibiótico', 'Infecções bacterianas, cistite'),
('Cloridrato de Sibutramina', 'Genérico', 'Inibidor de recaptação de serotonina e noradrenalina (IRSN)', 'Obesidade'),
('Diclofenaco Potássico', 'Genérico', 'Anti-inflamatório não esteroide (AINE)', 'Dor muscular, inflamação'),
('Budesonida', 'Genérico', 'Corticosteroide', 'Asma, doença pulmonar obstrutiva crônica (DPOC)'),
('Carbonato de Lítio', 'Genérico', 'Estabilizador de humor', 'Transtorno bipolar'),
('Cloridrato de Ciclobenzaprina', 'Genérico', 'Relaxante muscular', 'Espasmos musculares, dor lombar'),
('Candesartana Cilexetila', 'Genérico', 'Bloqueador do receptor de angiotensina II', 'Hipertensão arterial, insuficiência cardíaca'),
('Escitalopram', 'Genérico', 'Inibidor seletivo da recaptação de serotonina (ISRS)', 'Depressão, transtorno de ansiedade generalizada (TAG)'),
('Rosuvastatina Cálcica', 'Genérico', 'Estatina', 'Colesterol alto, prevenção de doenças cardiovasculares'),
('Sulfato de Neomicina', 'Genérico', 'Antibiótico', 'Infecções bacterianas, queimaduras'),
('Risperidona', 'Genérico', 'Antipsicótico', 'Esquizofrenia, transtorno bipolar'),
('Cloridrato de Cetirizina', 'Genérico', 'Antialérgico', 'Rinite alérgica, urticária'),
('Cloridrato de Paroxetina', 'Genérico', 'Inibidor seletivo da recaptação de serotonina (ISRS)', 'Depressão, transtorno de ansiedade'),
('Valsartana', 'Genérico', 'Bloqueador do receptor de angiotensina II', 'Hipertensão arterial, insuficiência cardíaca'),
('Cefuroxima Axetila', 'Genérico', 'Antibiótico', 'Infecções bacterianas, sinusite'),
('Fexofenadina', 'Genérico', 'Antialérgico', 'Rinite alérgica, urticária'),
('Nifedipino', 'Genérico', 'Bloqueador dos canais de cálcio', 'Hipertensão arterial, angina'),
('Metronidazol + Nistatina', 'Genérico', 'Antibiótico e antifúngico', 'Infecções bacterianas e fúngicas, vaginite'),
('Cetotifeno', 'Genérico', 'Antialérgico', 'Asma, rinite alérgica'),
('Drospirenona + Etinilestradiol', 'Genérico', 'Anticoncepcional oral combinado', 'Contracepção'),
('Sulfametoxazol + Trimetoprima', 'Genérico', 'Antibiótico', 'Infecções bacterianas, infecções do trato urinário'),
('Atenolol', 'Genérico', 'Bloqueador beta-adrenérgico', 'Hipertensão arterial, angina'),
('Amoxicilina + Clavulanato de Potássio', 'Genérico', 'Antibiótico', 'Infecções bacterianas, sinusite'),
('Rivotril', 'Genérico', 'Benzodiazepínico', 'Ansiedade, epilepsia'),
('Clobetasol', 'Genérico', 'Corticosteroide', 'Dermatite, psoríase'),
('Cloridrato de Metadona', 'Genérico', 'Analgésico opioide', 'Dor moderada a severa, terapia de substituição de opioides'),
('Fluoxetina', 'Genérico', 'Inibidor seletivo da recaptação de serotonina (ISRS)', 'Depressão, transtorno obsessivo-compulsivo (TOC)'),
('Sinvastatina + Ezetimiba', 'Genérico', 'Estatina + inibidor da absorção do colesterol', 'Colesterol alto'),
('Levoletiracetam', 'Genérico', 'Anticonvulsivante', 'Epilepsia'),
('Doxiciclina', 'Genérico', 'Antibiótico', 'Infecções bacterianas, acne'),
('Telmisartana', 'Genérico', 'Bloqueador do receptor de angiotensina II', 'Hipertensão arterial, insuficiência cardíaca'),
('Furosemida', 'Genérico', 'Diurético de alça', 'Hipertensão arterial, edema'),
('Cloridrato de Fluoxetina', 'Genérico', 'Inibidor seletivo da recaptação de serotonina (ISRS)', 'Depressão, transtorno obsessivo-compulsivo (TOC)'),
('Loperamida', 'Genérico', 'Antidiarreico', 'Diarreia'),
('Cetoprofeno', 'Genérico', 'Anti-inflamatório não esteroide (AINE)', 'Dor muscular, inflamação'),
('Nimesulida + Cetoprofeno', 'Genérico', 'Anti-inflamatório não esteroide (AINE)', 'Dor muscular, inflamação'),
('Sinvastatina + Atorvastatina', 'Genérico', 'Estatina', 'Colesterol alto'),
('Cloridrato de Betaxolol', 'Genérico', 'Bloqueador beta-adrenérgico', 'Glaucoma, hipertensão arterial'),
('Cloridrato de Bupropiona', 'Genérico', 'Antidepressivo atípico', 'Depressão, cessação do tabagismo'),
('Hidroxicloroquina', 'Genérico', 'Agente antimalárico', 'Malária, artrite reumatoide'),
('Cetoprofeno + Cloridrato de Ciclobenzaprina', 'Genérico', 'Anti-inflamatório + relaxante muscular', 'Dor muscular, inflamação'),
('Clonazepam', 'Genérico', 'Benzodiazepínico', 'Ansiedade, distúrbios do sono'),
('Cloridrato de Tansulosina', 'Genérico', 'Bloqueador alfa-adrenérgico', 'Hiperplasia prostática benigna'),
('Cloridrato de Fluoxetina + Cloridrato de Bupropiona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina + antidepressivo atípico', 'Depressão, transtorno depressivo maior'),
('Sinvastatina + Rosuvastatina', 'Genérico', 'Estatina', 'Colesterol alto'),
('Cloridrato de Metformina', 'Genérico', 'Hipoglicemiante', 'Diabetes tipo 2'),
('Cloridrato de Fexofenadina', 'Genérico', 'Antialérgico', 'Rinite alérgica, urticária'),
('Miconazol', 'Genérico', 'Antifúngico', 'Infecções fúngicas, candidíase'),
('Difosfato de Cloroquina', 'Genérico', 'Agente antimalárico', 'Malária, artrite reumatoide'),
('Cloridrato de Metoclopramida', 'Genérico', 'Antiemético', 'Náuseas, vômitos'),
('Cloridrato de Nortriptilina', 'Genérico', 'Antidepressivo tricíclico', 'Depressão, dor crônica'),
('Paracetamol + Cafeína', 'Genérico', 'Analgésico', 'Dor de cabeça, febre'),
('Cloridrato de Tiamina', 'Genérico', 'Vitamina B1', 'Deficiência de tiamina'),
('Cloridrato de Donepezila', 'Genérico', 'Inibidor da acetilcolinesterase', 'Doença de Alzheimer, demência'),
('Cloridrato de Metadona + Cloridrato de Ciclobenzaprina', 'Genérico', 'Analgésico opioide + relaxante muscular', 'Dor moderada a severa, espasmos musculares'),
('Cloridrato de Ciclobenzaprina + Diclofenaco Sódico', 'Genérico', 'Relaxante muscular + anti-inflamatório não esteroide (AINE)', 'Espasmos musculares, inflamação'),
('Carbonato de Cálcio + Colecalciferol', 'Genérico', 'Suplemento de cálcio e vitamina D', 'Deficiência de cálcio, prevenção de osteoporose'),
('Cloridrato de Amiodarona', 'Genérico', 'Antiarrítmico', 'Arritmias cardíacas, fibrilação atrial'),
('Cloridrato de Loperamida', 'Genérico', 'Antidiarreico', 'Diarreia'),
('Cloridrato de Ranitidina', 'Genérico', 'Antagonista dos receptores H2', 'Úlcera péptica, refluxo ácido'),
('Cloridrato de Hidroxizina', 'Genérico', 'Antialérgico', 'Urticária, dermatite'),
('Cloridrato de Ciclobenzaprina + Paracetamol', 'Genérico', 'Relaxante muscular + analgésico', 'Espasmos musculares, dor'),
('Levocetirizina', 'Genérico', 'Antialérgico', 'Rinite alérgica, urticária'),
('Cloridrato de Bupropiona + Naltrexona', 'Genérico', 'Antidepressivo atípico + antagonista dos receptores opioides', 'Obesidade, cessação do tabagismo'),
('Carbonato de Lítio + Cloreto de Potássio', 'Genérico', 'Estabilizador de humor + suplemento de potássio', 'Transtorno bipolar, deficiência de potássio'),
('Cloridrato de Amitriptilina + Cloridrato de Amitriptilina + Cloridrato de Clorpromazina', 'Genérico', 'Analgésico opioide + antidepressivo tricíclico + neuroléptico', 'Dor neuropática, depressão resistente ao tratamento'),
('Cloridrato de Metadona + Naloxona', 'Genérico', 'Analgésico opioide + antagonista dos receptores opioides', 'Dor moderada a severa, terapia de substituição de opioides'),
('Cloridrato de Benazepril', 'Genérico', 'Inibidor da enzima conversora de angiotensina (IECA)', 'Hipertensão arterial, insuficiência cardíaca'),
('Cloridrato de Ondansetrona', 'Genérico', 'Antiemético', 'Náuseas, vômitos'),
('Cloridrato de Tramadol + Paracetamol', 'Genérico', 'Analgésico opioide + analgésico', 'Dor moderada a severa'),
('Sinvastatina + Losartana Potássica', 'Genérico', 'Estatina + bloqueador do receptor de angiotensina II', 'Colesterol alto, hipertensão arterial'),
('Cloridrato de Lidocaína', 'Genérico', 'Anestésico local', 'Anestesia tópica, procedimentos médicos'),
('Cloridrato de Venlafaxina', 'Genérico', 'Inibidor seletivo da recaptação de serotonina e noradrenalina (IRSN)', 'Depressão, transtorno de ansiedade generalizada (TAG)'),
('Brometo de Otilônio', 'Genérico', 'Antiespasmódico', 'Síndrome do intestino irritável, cólicas abdominais'),
('Cloridrato de Doxiciclina', 'Genérico', 'Antibiótico', 'Infecções bacterianas, acne'),
('Cloridrato de Desloratadina', 'Genérico', 'Antialérgico', 'Rinite alérgica, urticária'),
('Cloridrato de Dicloridrato de Cetotifeno', 'Genérico', 'Antialérgico', 'Asma, rinite alérgica'),
('Sulfato de Neomicina + Bacitracina', 'Genérico', 'Antibiótico tópico', 'Feridas, infecções cutâneas'),
('Cloridrato de Labetalol', 'Genérico', 'Bloqueador alfa e beta-adrenérgico', 'Hipertensão arterial, emergência hipertensiva'),
('Cloridrato de Duloxetina', 'Genérico', 'Inibidor seletivo da recaptação de serotonina e noradrenalina (IRSN)', 'Depressão, transtorno de ansiedade generalizada (TAG)'),
('Cloridrato de Donepezila + Cloridrato de Memantina', 'Genérico', 'Inibidor da acetilcolinesterase + antagonista do receptor NMDA', 'Doença de Alzheimer, demência'),
('Cloridrato de Meclizina', 'Genérico', 'Anti-histamínico', 'Náuseas, vertigem'),
('Brometo de Ipratrópio', 'Genérico', 'Broncodilatador', 'Doença pulmonar obstrutiva crônica (DPOC), bronquite'),
('Cloridrato de Dapagliflozina', 'Genérico', 'Inibidor do cotransportador de sódio-glicose 2 (SGLT2)', 'Diabetes tipo 2'),
('Cloridrato de Topiramato', 'Genérico', 'Anticonvulsivante', 'Epilepsia, enxaqueca'),
('Cloridrato de Fluoxetina + Cloridrato de Bupropiona + Naltrexona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina + antidepressivo atípico + antagonista dos receptores opioides', 'Obesidade, depressão'),
('Cloridrato de Venlafaxina + Cloridrato de Bupropiona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina e noradrenalina (IRSN) + antidepressivo atípico', 'Depressão, transtorno de ansiedade generalizada (TAG)'),
('Cloridrato de Betametasona', 'Genérico', 'Corticosteroide', 'Inflamações, alergias'),
('Sulfato de Condroitina + Sulfato de Glucosamina', 'Genérico', 'Suplemento para saúde das articulações', 'Osteoartrite, dores articulares'),
('Cloridrato de Tansulosina + Dutasterida', 'Genérico', 'Bloqueador alfa-adrenérgico + inibidor da 5-alfa-redutase', 'Hiperplasia prostática benigna'),
('Cloridrato de Memantina', 'Genérico', 'Antagonista do receptor NMDA', 'Doença de Alzheimer, demência'),
('Cloridrato de Sertralina + Cloridrato de Bupropiona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina + antidepressivo atípico', 'Depressão, transtorno de ansiedade generalizada (TAG)'),
('Cloridrato de Dapagliflozina + Cloridrato de Metformina', 'Genérico', 'Inibidor do cotransportador de sódio-glicose 2 (SGLT2) + hipoglicemiante', 'Diabetes tipo 2'),
('Cloridrato de Sotalol', 'Genérico', 'Bloqueador beta-adrenérgico', 'Arritmias cardíacas, taquicardia'),
('Cloridrato de Metoclopramida + Dimeticona', 'Genérico', 'Antiêmético + antiflatulento', 'Náuseas, flatulência'),
('Cloridrato de Benzonatato', 'Genérico', 'Antitussígeno', 'Tosse'),
('Cloridrato de Mebeverina', 'Genérico', 'Antiespasmódico', 'Síndrome do intestino irritável, cólicas abdominais'),
('Cloridrato de Duloxetina + Cloridrato de Bupropiona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina e noradrenalina (IRSN) + antidepressivo atípico', 'Depressão, transtorno de ansiedade generalizada (TAG)'),
('Cloridrato de Terbinafina', 'Genérico', 'Antifúngico', 'Infecções fúngicas, pé de atleta'),
('Cloridrato de Metformina + Cloridrato de Saxagliptina', 'Genérico', 'Hipoglicemiante', 'Diabetes tipo 2'),
('Cloridrato de Pramipexol', 'Genérico', 'Agonista dopaminérgico', 'Doença de Parkinson, síndrome das pernas inquietas'),
('Carbonato de Cálcio + Vitamina D3', 'Genérico', 'Suplemento de cálcio e vitamina D', 'Deficiência de cálcio, prevenção de osteoporose'),
('Cloridrato de Hidroxizina + Cloridrato de Ranitidina', 'Genérico', 'Antialérgico + antagonista dos receptores H2', 'Urticária, refluxo ácido'),
('Cloridrato de Metilfenidato', 'Genérico', 'Estimulante do sistema nervoso central', 'Transtorno do déficit de atenção e hiperatividade (TDAH)'),
('Cloridrato de Metoclopramida + Dimeticona + Hioscina', 'Genérico', 'Antiêmético + antiflatulento + antiespasmódico', 'Náuseas, flatulência, cólicas abdominais'),
('Cloridrato de Venlafaxina + Cloridrato de Bupropiona + Naltrexona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina e noradrenalina (IRSN) + antidepressivo atípico + antagonista dos receptores opioides', 'Depressão, transtorno de ansiedade generalizada (TAG), obesidade'),
('Cloridrato de Amiodarona + Sinvastatina', 'Genérico', 'Antiarrítmico + estatina', 'Arritmias cardíacas, colesterol alto'),
('Cloridrato de Fexofenadina + Cloridrato de Pseudoefedrina', 'Genérico', 'Antialérgico + descongestionante', 'Rinite alérgica, congestão nasal'),
('Cloridrato de Sertralina + Cloridrato de Bupropiona + Naltrexona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina + antidepressivo atípico + antagonista dos receptores opioides', 'Depressão, transtorno de ansiedade generalizada (TAG), obesidade'),
('Cloridrato de Pramipexol + Cloridrato de Carbidopa + Levodopa', 'Genérico', 'Agonista dopaminérgico + inibidor da descarboxilase da dopa + precursor da dopamina', 'Doença de Parkinson'),
('Cloridrato de Trazodona', 'Genérico', 'Antidepressivo', 'Depressão, transtorno de ansiedade'),
('Cloridrato de Metformina + Vildagliptina', 'Genérico', 'Hipoglicemiante', 'Diabetes tipo 2'),
('Cloridrato de Amitriptilina + Cloridrato de Clorpromazina + Cloridrato de Levomepromazina', 'Genérico', 'Antidepressivo tricíclico + neuroléptico fenotiazínico', 'Depressão, esquizofrenia'),
('Cloridrato de Mirtazapina', 'Genérico', 'Antidepressivo', 'Depressão, transtorno de ansiedade'),
('Cloridrato de Tolterodina', 'Genérico', 'Antimuscarínico', 'Bexiga hiperativa, incontinência urinária'),
('Cloridrato de Venlafaxina + Cloridrato de Bupropiona + Naltrexona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina e noradrenalina (IRSN) + antidepressivo atípico + antagonista dos receptores opioides', 'Depressão, transtorno de ansiedade generalizada (TAG), obesidade'),
('Cloridrato de Tansulosina + Dutasterida', 'Genérico', 'Bloqueador alfa-adrenérgico + inibidor da 5-alfa-redutase', 'Hiperplasia prostática benigna'),
('Cloridrato de Trazodona + Cloridrato de Nortriptilina', 'Genérico', 'Antidepressivo + antidepressivo tricíclico', 'Depressão, transtorno de ansiedade'),
('Cloridrato de Terazosina', 'Genérico', 'Bloqueador alfa-adrenérgico', 'Hipertensão arterial, hiperplasia prostática benigna'),
('Cloridrato de Mirtazapina + Cloridrato de Venlafaxina', 'Genérico', 'Antidepressivo + inibidor seletivo da recaptação de serotonina e noradrenalina (IRSN)', 'Depressão, transtorno de ansiedade'),
('Cloridrato de Ranolazina', 'Genérico', 'Inibidor da corrente de sódio tardia', 'Angina'),
('Cloridrato de Budesonida + Formoterol', 'Genérico', 'Corticosteroide + agonista beta-2 adrenérgico', 'Asma, doença pulmonar obstrutiva crônica (DPOC)'),
('Cloridrato de Sildenafila', 'Genérico', 'Inibidor da fosfodiesterase tipo 5 (PDE5)', 'Disfunção erétil'),
('Cloridrato de Sertralina + Cloridrato de Bupropiona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina + antidepressivo atípico', 'Depressão, transtorno de ansiedade generalizada (TAG)'),
('Cloridrato de Tansulosina + Finasterida', 'Genérico', 'Bloqueador alfa-adrenérgico + inibidor da 5-alfa-redutase', 'Hiperplasia prostática benigna'),
('Cloridrato de Sildenafila + Tadalafila', 'Genérico', 'Inibidor da fosfodiesterase tipo 5 (PDE5)', 'Disfunção erétil'),
('Cloridrato de Ranitidina + Oxetacaina', 'Genérico', 'Antagonista dos receptores H2 + anestésico local', 'Úlcera péptica, dor abdominal'),
('Cloridrato de Tansulosina + Dutasterida + Sulfato de Alfa Tocoferol', 'Genérico', 'Bloqueador alfa-adrenérgico + inibidor da 5-alfa-redutase + vitamina E', 'Hiperplasia prostática benigna'),
('Cloridrato de Ranitidina + Simeticona', 'Genérico', 'Antagonista dos receptores H2 + antiflatulento', 'Úlcera péptica, flatulência'),
('Cloridrato de Metoclopramida + Dimeticona + Trimebutina', 'Genérico', 'Antiêmético + antiflatulento + antiespasmódico', 'Náuseas, flatulência, cólicas abdominais'),
('Cloridrato de Sertralina + Cloridrato de Bupropiona + Naltrexona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina + antidepressivo atípico + antagonista dos receptores opioides', 'Depressão, transtorno de ansiedade generalizada (TAG), obesidade'),
('Cloridrato de Tamsulosina + Dutasterida', 'Genérico', 'Bloqueador alfa-adrenérgico + inibidor da 5-alfa-redutase', 'Hiperplasia prostática benigna'),
('Cloridrato de Ranitidina + Lidocaína', 'Genérico', 'Antagonista dos receptores H2 + anestésico local', 'Úlcera péptica, dor abdominal'),
('Cloridrato de Nortriptilina + Cloridrato de Amitriptilina', 'Genérico', 'Antidepressivo tricíclico', 'Depressão, dor crônica'),
('Cloridrato de Prazosina', 'Genérico', 'Bloqueador alfa-adrenérgico', 'Hipertensão arterial, hiperplasia prostática benigna'),
('Cloridrato de Sildenafila + Dapoxetina', 'Genérico', 'Inibidor da fosfodiesterase tipo 5 (PDE5) + inibidor seletivo da recaptação de serotonina (ISRS)', 'Disfunção erétil, ejaculação precoce'),
('Cloridrato de Sertralina + Cloridrato de Bupropiona + Naltrexona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina + antidepressivo atípico + antagonista dos receptores opioides', 'Depressão, transtorno de ansiedade generalizada (TAG), obesidade'),
('Cloridrato de Sertralina + Cloridrato de Bupropiona', 'Genérico', 'Inibidor seletivo da recaptação de serotonina + antidepressivo atípico', 'Depressão, transtorno de ansiedade generalizada (TAG)'),
('Cloridrato de Ranitidina + Dimeticona', 'Genérico', 'Antagonista dos receptores H2 + antiflatulento', 'Úlcera péptica, flatulência'),
('Cloridrato de Sildenafil + Dapoxetine', 'Genérico', 'Inibidor da fosfodiesterase tipo 5 (PDE5) + inibidor seletivo da recaptação de serotonina (ISRS)', 'Disfunção erétil, ejaculação precoce'),
('Cloridrato de Sildenafil + Tadalafil', 'Genérico', 'Inibidor da fosfodiesterase tipo 5 (PDE5)', 'Disfunção erétil'),
('Cloridrato de Ranitidina + Dimeticona + Omeprazol', 'Genérico', 'Antagonista dos receptores H2 + antiflatulento + inibidor de bomba de prótons', 'Úlcera péptica, flatulência, refluxo ácido'),
('Cloridrato de Tansulosina + Dutasterida + Sulfato de Alfa Tocoferol', 'Genérico', 'Bloqueador alfa-adrenérgico + inibidor da 5-alfa-redutase + vitamina E', 'Hiperplasia prostática benigna'),
('Cloridrato de Omeprazol + Bicarbonato de Sódio', 'Genérico', 'Inibidor de bomba de prótons + antiácido', 'Refluxo ácido, úlcera péptica'),
('Cloridrato de Terbinafina + Cloridrato de Ciclopirox', 'Genérico', 'Antifúngico tópico', 'Micose, onicomicose'),
('Cloridrato de Terazosina + Finasterida', 'Genérico', 'Bloqueador alfa-adrenérgico + inibidor da 5-alfa-redutase', 'Hipertensão arterial, hiperplasia prostática benigna');
